-- Consultas día Martes 22 Junio.
select * from libro where ejemplares>33;
select *from Empleado1 where sueldo>500000.00;
select *from libro where autor='Albertopijo'and edicion='Primera edición';
select * from libro where edicion='Primera edición';
select *from Empleado1 where departamento='Comunicaciones';
select* from alumno where curso='8ºB';
select * from alumno;
select * from alumno where curso='8ºB' and edad>=12;
select * from alumno where edad >10 and promedio >=6.50;
select * from alumno where edad<8 and promedio >=6.00;
select * from Empleado1 where edad in (24,27,29);
select * from Empleado1;
select * from libro where edicion='Primera Edición' and autor in ('Grillo', 'Floripondio', 'Manolo Sanchez');
select  nombre,apellidoP, ApellidoM from Empleado1 where departamento= 'ServicioCliente';
select nombre, apellidoP, curso from alumno where promedio>=6.00;
select * from Empleado1 where departamento not in ('RecursosHumanos','ServicioCliente');
select * from Libro where edicion not in ('Primera Edición');
select *from alumno where edad not in (5,4,6,7) and curso not in ('4ºB','4ºA','5ºB','5ºA');
select * from Empleado1 where cargo <>'teleoperador';
select * from libro where edicion <> 'Primera Edición';
select * from alumno where curso <> '8ºB';
select * from Empleado1 where edad between 30 and 40;
select *from libro where ejemplares between 50 and 100;
select * from alumno where promedio between 5.00 and 7.00;
select * from alumno where notas between 5.50 and 6.00;
select * from Empleado1 where nombre like 'M%';
select * from Libro where autor like 'a%';
select * from alumno where nombre like '%s';
select * from alumno where apellidoP like 'M%';
