-- Miércoles 23 Junio
Select * from libro where editorial not in ('Chamullo','Conventillo','Salavatore','Balmaseda');
select nombre, editorial, ejemplares from libro where ejemplares between 100 and 330;
select nombre, apellidoP, cargo from Empleado1 where sueldo between 500000.00 and 650000.00;
select nombre, apellidoP, apellidoM, cargo, departamento, edad from Empleado1 where departamento not in  ('ServicioCliente');
select * from Alumno order by edad;
select * from Libro order by ejemplares desc;
select nombre, Edicion from libro order by nombre asc;
select nombre, cargo, edad from Empleado1 order by edad;
select apellidoP,nombre, cargo,fechaIngreso from Empleado1 order by fechaIngreso desc;
select *from Empleado1 order by cargo asc;
select nombre, apellidoP, cargo, departamento from Empleado1 order by departamento asc;
select nombre, cargo, sueldo from Empleado1 order by sueldo desc;
select nombre, cargo, sueldo from Empleado1 order by sueldo asc;
select autor, nombre, editorial from libro order by editorial;
select * from libro order by ejemplares desc;
select count(id_Empleado) as cantidad from Empleado1;
select count(id_Libro) as cantidadL from libro;
select count(id_Alumno) as cantidad from alumno;
select count(id_Alumno) as mayores from alumno where edad<10;
select max(edad) from alumno;
select min(edad) from alumno;
select max(edad) from Empleado1 where departamento='ServicioCliente';
select min(ejemplares) from libro where edicion='Primera Edición';
select max(ejemplares) from libro where edicion='Segunda Edición' and añoPublicacion>2005-01-01;
select min(añoPublicacion) from libro where edicion='Primera Edición';
select sum(sueldo) from Empleado1;
select sum(edad) from alumno;
select sum(ejemplares) from libro;
select avg(sueldo) from Empleado1;
select avg(promedio) from alumno;
select avg (ejemplares) from libro;